version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - pip install --upgrade pip
      - pip install virtualenv
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
      - echo Running on account $ACCOUNT_ID
      - echo Lambdas will use role $LAMBDA_ROLE_ARN
      - sed "s^SOME_ROLE_PATCHED_BY_BUILD_SPEC^$LAMBDA_ROLE_ARN^" policies-$ACCOUNT_ID.yml > policies.yml
      - sed -i "s^SOME_NOTIFICATION_TOPIC_PATCHED_BY_BUILD_SPEC^$NOTIFY_SNS_TOPIC_ARN^" policies.yml
      - sed -i "s^ACCOUNT_ID_PATCHED_BY_BUILD_SPEC^$ACCOUNT_ID^" policies.yml


      - virtualenv --python=python2 custodian
      - . custodian/bin/activate
      - pip install c7n
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - custodian run -s . policies.yml
    finally:
      - echo This always runs even if the update or install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`