# Environment dependencies:
# - LAMBDA_ROLE_ARN ARN for the role the Cloud Custodian Lambdas uses
# - ACCOUNT_ID The 12 digit account ID this is running on
# - NOTIFY_SNS_TOPIC_ARN Topic Cloud Custodian uses when notify action is used.
# - GITHUB_TOKEN Token for accessing GitHub
# - GITHUB_OWNER The name of the repository owner
# - GITHUB_REPO The repository name

version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install jq -y
      - pip install --upgrade pip
      - pip install virtualenv
      - set
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo GitHub commit SHA $CODEBUILD_RESOLVED_SOURCE_VERSION
      - |-
        curl -s -H "Authorization: token $GITHUB_TOKEN" -H "user-agent: node.js" https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/commits/$CODEBUILD_RESOLVED_SOURCE_VERSION |jq ".files[].filename" | grep "policies" | sed "s/\"policies-//" | sed "s/.yml\"//" | grep "$ACCOUNT_ID" > /tmp/changed_github_files.txt
      - CONTAINS_THIS_ACCOUNT=`cat /tmp/changed_github_files.txt | wc -l`
      - if [ "$CONTAINS_THIS_ACCOUNT" -eq 0 ]; then exit 0; fi
      - virtualenv --python=python2 custodian
      - . custodian/bin/activate
      - pip install c7n

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - sed "s^SOME_ROLE_PATCHED_BY_BUILD_SPEC^$LAMBDA_ROLE_ARN^" policies-$ACCOUNT_ID.yml > policies.yml
      - sed -i "s^SOME_NOTIFICATION_TOPIC_PATCHED_BY_BUILD_SPEC^$NOTIFY_SNS_TOPIC_ARN^" policies.yml
      - sed -i "s^ACCOUNT_ID_PATCHED_BY_BUILD_SPEC^$ACCOUNT_ID^" policies.yml
      - custodian run -s . -c policies.yml -v
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

# If environment specific stuff is needed
# -------------------------------------------
#build:
#     commands:
#       - echo "${CODEBUILD_BUILD_ARN}"
#       - |
#         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/MyProjectDev-" >/dev/null; then
#           yarn run build-dev;
#         fi
#       - |
#         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/MyProject-" >/dev/null; then
#           yarn run build-prod;
#         fi